### ISSUE TITLE
Collaborative edit loses sync without warning

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#124]
At one point, a dual-laptop quest edit session fell out of sync. At one point, both devices were suspended for ~30 minutes, so that could be part of the problem.

More significantly, we should alert when the device loses contact so the user can refresh the page and/or backup their quest content.

**Comment by toddmedema** [comment]
Yea, that's definitely a bug. I'd also bet it's an issue 

Picturing the UX here being a larger, red bar appearing on the top saying something like "Connection lost. Attempting to reconnect...", whilst in the background running whatever code is needed to re-establish the connection
