### ISSUE TITLE
Operation debugging

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#129]
We should have a way to:

- Set initial op values when loading new cards
- See all currently set variables while previewing a quest
- See variables specific to the card being displayed
- Edit any variables, but also variables specific to the card being displayed.

**Comment by toddmedema** [comment]
To clarify, "variables specific to the card being displayed" means variables that're referenced in context elements on the currently visible card?

**Comment by smartin015** [comment]
Yep

**Comment by smartin015** [comment]
Fixed with #70
