### ISSUE TITLE
Discuss: Default card titles for on win and on lose?

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#143]
@smartin015 ie "Victory" and "Defeat" if they don't give them titles?

Trying to think a) is there any downside / reason not to from a writing perspective and b) any reason from a technical perspective

**Comment by smartin015** [comment]
It could be confusing if there's a pyrrhic victory, e.g. you slay the lich but then the lich kills everyone in the city. Not very victorious...

**Comment by toddmedema** [comment]
Fair, closing to stay focused
