### ISSUE TITLE
Branching with over 5 indentations yields error 501

### ISSUE THREAD

**Issue by danielwiktorczyk** [Fabricate-IO/expedition-quest-creator#144]
I've been encountering this problem several times when my branches become over 5 indentations long. It's solved with a **goto** redirect, but it's inconvenient to have to resort to it at times.

**Comment by toddmedema** [comment]
That's no good! Adding this to our next bug sprint

**Comment by toddmedema** [comment]
@danielwiktorczyk good news! Just fixed it https://github.com/Fabricate-IO/expedition-quest-creator/pull/156
