### ISSUE TITLE
Quest Ideas!

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#149]
Looking for a fun, unusual quest idea to create? Here's a great place to brainstorm - and feel free to use any of the ideas.

- Traitor. Min 2 players. As part of setup, one player is randomly assigned the traitor role, and given secret instructions. You could also give separate, secret instructions to non-traitor players.
- Hidden identity. Like traitor, but EVERYONE gets their own secret objectives! Could be as simple as "have the most loot at the end", or "get the party to make a specific decision" (such as getting them captured by the bad guy)
- Resource management. Perhaps you only have a few days of food, and you have to figure how to survive. Opportunities to potentially gather more food vs escape vs try to get rescued.
- Puzzles and riddles. Turn existing, well known puzzles and riddles into quests.

**Comment by smartin015** [comment]
Theme idea: exploring the mind of someone in a coma, in a similar format as the dialog-only [Lifeline ](https://play.google.com/store/apps/details?id=com.threeminutegames.lifeline.google&hl=en) game.

**Comment by toddmedema** [comment]
Moved to a Reddit thread for better visibility + commenting system: https://www.reddit.com/r/expeditionrpg/comments/5p4oq2/quest_ideas_brainstorming_and_sharing/
