### ISSUE TITLE
Urgent: realtime loses sync when offline during re-auth

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#153]
Seems like restarting the server (ie deploying updates resets auth).

And, when that happens, seems like it breaks saving?

Ideally, users shouldn't even have to refresh the page. Perhaps if saving fails / the app realizes auth broke, it tries to re-authenticate in the background? If that turns out to not be an effective way of fixing it, we could potentially save the editor contents to local storage, refresh the page, and insert them.

That being said, any time it loses sync, there's a problem: if there's a mismatch between what's on the server and what's in the editor (mainly in the case of collaborative editing), we'll have to somehow present the two versions to the user and let them sort out the diff... (joy)

But, that can be a separate issue. First and foremost, we need to prevent users from losing data!

Also, as part of this, ANY TIME saving isn't working, should show a big red bar on the top alerting the user that the connection is lost

**Comment by danielwiktorczyk** [comment]
Not sure if it's related, but I've had a big problem in which:
- my editor stated that everything was saved (after having done a lot of editing)
- I published my quest afterward 
- discovered that when reopening the editor, my quest code reverted to an older version *before* I had published my quest
- the published quest had retained the latest edits, unbroken

**Comment by toddmedema** [comment]
@danielwiktorczyk roger. We found the cause! The quest is actually saving to drive just fine, so you might be able to dig up your previous changes in the drive file version history. We're currently figuring out how to fix the bug so that this won't happen again,

Related / this should also fix https://github.com/Fabricate-IO/expedition-quest-creator/issues/124
