### ISSUE TITLE
Improved + additional unit tests

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#16]
Besides generally adding more tests, we can also get fancy and combine the error documentation + error test cases. Right now, we have to duplicate "good / doesn't throw error X" and "bad / throws error X" examples across documentation and tests, but would save significant maintenance effort (+ result in better tests + documentation) to have them specified in the same file + auto-generated

**Comment by toddmedema** [comment]
Updated with more info / ideas!
