### ISSUE TITLE
Transition text adjustment

### ISSUE THREAD

**Issue by danielwiktorczyk** [Fabricate-IO/expedition-quest-creator#165]
Sometimes, you don't want to make a whole new branch, but still want to say something specific instead of the default "Next". For example, if you'd want the transition to be "Proceed", we'd currently have to do something like this 

```
_Card A_

Text

* Proceed

  _Card B_ 

  **end**

```

vs something more like the following would be cleaner, as to not create a new branch. In this case, I'm using the syntax just like that in `**end**` to create a single choice that would replace the default "next" that pops up when we have a card that follows the other. 

```
_Card A_

text

**next Proceed**

_Card B_

**end**
```
Thus, on ```_Card A_```, there will be the one choice that moves on to ```_Card B_``` with text "Proceed" rather than "Next"

**Comment by danielwiktorczyk** [comment]
P.s.: I'm not able to myself add labels on issues, so that's why an "enhancement" isn't labeled here

**Comment by smartin015** [comment]
Gotcha. Would something like:

```markdown
_Card A_

Text

* Proceed

  **goto next**

_Card B_
...

```

work?

**Comment by danielwiktorczyk** [comment]
If that means the same as 

```
_Card A_

Text

* Proceed

  **goto cardb**

_Card B_ (#cardb)
```
, then it would!, but writing something like

```
_Card A_

Text

**next Proceed**

_Card B_ 
```

where the syntax `**next TransitionText**` would be easiest and swift to write in place of what currently takes 3 lines to type each time. (or 2, using the `goto next` idea)

**Comment by toddmedema** [comment]
Sounds like we're already planning on adding the special `**next**` option (https://github.com/Fabricate-IO/expedition-quest-creator/issues/162), so we'll start by rolling that out, and we can revisit more custom syntax if needed :)
