### ISSUE TITLE
Show preview of quest as nodes before publishing

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#175]
Assuming we go the route of nodal visualization, it'd be really cool to offer users a diff of their current quest vs the published quest, with deleted/added nodes visualized.

**Comment by toddmedema** [comment]
Good idea! Since node view is a huge separate thing / not currently on the roadmap, added this to future idea dump: https://github.com/Fabricate-IO/expedition-quest-creator/issues/27
