### ISSUE TITLE
Add support for random enemies

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#196]
Creating a dungeon crawl mode will be much easier if we add support in quests for the idea of a "random enemy", "random tier 1", "random beast" or a "random tier 1 beast" (essentially `random [tier] [class]`)

Though, before implementing this, wanted to check with @smartin015 around syntax. Would it make sense to have that be the official quest creator / QDL syntax? (the other option I can think of would be a JSON object, which might be more computer-friendly, but seems much less human friendly - esp since we've managed to otherwise avoid JSON in the quest creator so far!)

**Comment by smartin015** [comment]
I think that this drives home the need for a preset list of functions/methods for users of ops. 

This seems very close to programmatic, which isn't something that regular QDL should need or have - I think it would be better suited as an already-defined function available within the op scope. To the user, this'd look something like:

`-  {{_.randomEnemy(1, "beast")}}`

Or perhaps more readably:

`- {{_.randomBeastWithTier(1)}}`

And underneath the hood, the JS function would choose from our known list of baddies. No extra syntax is needed, and the randomness is appropriately treated as programmatic logic.

**Comment by toddmedema** [comment]
That makes sense. So, sounds like the issue-before-the-issue is implementing the `_` namespace

**Comment by toddmedema** [comment]
Fun note: mathjs only works with double quotes for strings, throws weird errors if you try to use single quotes
