### ISSUE TITLE
FAQ and loot usage

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#198]
- the Rogue's surge requires loot to be held by a single person, so we should mention that in the rules.
- Imbue: +5 to target's FIRST roll

**Comment by toddmedema** [comment]
@smartin015 created PR to mention loot change in app; also clarified loot section of rules (and added note to FAQ section for Imbue + updated Imbue card in card doc): https://github.com/Fabricate-IO/expedition-app/pull/240
