### ISSUE TITLE
roleplaying right after combat w/o title gets merged into pre-combat card?

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#75]
looks like combat after roleplaying must have a title? Create a test case

**Comment by smartin015** [comment]
Unsure if you mean combat after roleplaying or roleplaying after combat.

Combat doesn't make sense without a title... there's no way to tell if the user is making choices labeled "on win" and "on lose" along with a hyphenated list of things. We can try to infer what the user means, but that gets super tricky.

RP after combat? That should need a title header to disambiguate, but if it's getting merged into the card before it, then that's a bug.

**Comment by toddmedema** [comment]
roleplaying after combat:
```
_Start_

Hi

_combat_

- Skeleton Swordsman

* on win
 
  TODO
  
* on lose
 
  TODO

Next card
```
actually looks like it's silently breaking rendering right now. Trying to match `next card` against BlockRenderer.extractBulleted, fails
