### ISSUE TITLE
Comments directly after choices (Bug)

### ISSUE THREAD

**Issue by danielwiktorczyk** [Fabricate-IO/expedition-quest-creator#91]
Leaving `comments` directly after a `choice`, which is to say that are not directly after `text` seem to create a bug where 
- on the previous page, when viewing choices, there will be _two_ `choices` directly after the other that are the same, in which the first `choice` does not respond to selection, and the duplicate below will lead to the next page (but ignoring any `goto`s? I could test this when I have more time)

**Comment by danielwiktorczyk** [comment]
Here's a slightly different circumstance. 
<img width="868" alt="issue commenting" src="https://cloud.githubusercontent.com/assets/24488852/21077358/067d3966-bf17-11e6-9ed5-d4315b10b98a.png">

Note the `// Vault code ends // `
Here, the choice becomes doubled: the first being unresponsive, and the second works as normal. Not sure why this happens.

**Comment by toddmedema** [comment]
@danielwiktorczyk thanks for pointing this out, looking into it now! Cool GitHub trick - you can add labels (such as bug) via "labels" on the right hand side when creating issues, rather than appending it to the title :)

**Comment by toddmedema** [comment]
@danielwiktorczyk should be fixed on production! https://github.com/Fabricate-IO/expedition-quest-creator/pull/96
