### ISSUE TITLE
Prevent accidentally publishing the default quest to prod

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-creator#93]
Shouldn't allow them to publish when the title, summary, author or email is set to the default; will save us a lot of hassle in cleaning up the prod DB

**Comment by PanoramicPanda** [comment]
I have already done this so many times by accident.

**Comment by toddmedema** [comment]
Glad to know I'm not the only one :) @PanoramicPanda thanks for joining the conversation!

**Comment by toddmedema** [comment]
closed by https://github.com/Fabricate-IO/expedition-quest-creator/pull/98, rolling out to prod now
